import { PlaylistItem } from "@nomercy-entertainment/nomercy-video-player/src/types";

const playlist: PlaylistItem[] = [
	{
		id: 'sintel',
		title: 'Sintel',
		description: 'Sintel is an independently produced short film, initiated by the Blender Foundation as a means to further improve and validate the free/open source 3D creation suite Blender. With initial funding provided by 1000s of donations via the internet community, it has again proven to be a viable development model for both open 3D technology as for independent animation film.\nThis 15 minute film has been realized in the studio of the Amsterdam Blender Institute, by an international team of artists and developers. In addition to that, several crucial technical and creative targets have been realized online, by developers and artists and teams all over the world.\nwww.sintel.org',
		image: 'https://image.tmdb.org/t/p/w780/q2bVM5z90tCGbmXYtq2J38T5hSX.jpg',
		logo: 'https://image.tmdb.org/t/p/original/p3NwyW8Jf5AGmKk5B0K69MhiMWv.png',
		file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/media/master/Films/Films/Sintel.(2010)/Sintel.(2010).NoMercy.m3u8',
		duration: '14:48',
		// season: 1,
		episode: 1,
		year: 2010,
		rating: {
			rating: 6,
			image: 'NL/NL_6.svg',
		},
		tracks: [
			{
				id: 0,
				label: 'Dutch (Full)',
				file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/media/master/Films/Films/Sintel.(2010)/subtitles/Sintel.(2010).NoMercy.dut.full.vtt',
				language: 'dut',
				kind: 'subtitles',
			},
			{
				id: 1,
				label: 'English (Full)',
				type: 'sdh',
				file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/media/master/Films/Films/Sintel.(2010)/subtitles/Sintel.(2010).NoMercy.eng.full.vtt',
				language: 'eng',
				kind: 'subtitles',
			},
			{
				id: 2,
				label: 'French (Full)',
				file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/media/master/Films/Films/Sintel.(2010)/subtitles/Sintel.(2010).NoMercy.fre.full.vtt',
				language: 'fre',
				kind: 'subtitles',
			},
			{
				id: 3,
				label: 'German (Full)',
				type: 'sdh',
				file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/media/master/Films/Films/Sintel.(2010)/subtitles/Sintel.(2010).NoMercy.ger.full.vtt',
				language: 'ger',
				kind: 'subtitles',
			},
			{
				id: 4,
				label: 'Italian (Full)',
				file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/media/master/Films/Films/Sintel.(2010)/subtitles/Sintel.(2010).NoMercy.ita.full.vtt',
				language: 'ita',
				kind: 'subtitles',
			},
			{
				id: 5,
				label: 'Russian (Full)',
				file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/media/master/Films/Films/Sintel.(2010)/subtitles/Sintel.(2010).NoMercy.rus.full.vtt',
				language: 'rus',
				kind: 'subtitles',
			},
			{
				id: 6,
				label: 'German (Full)',
				file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/media/master/Films/Films/Sintel.(2010)/subtitles/Sintel.(2010).NoMercy.ger.full.vtt',
				language: 'ger',
				kind: 'subtitles',
			},
			{
				id: 7,
				label: 'Portuguese (Full)',
				file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/media/master/Films/Films/Sintel.(2010)/subtitles/Sintel.(2010).NoMercy.por.full.vtt',
				language: 'por',
				kind: 'subtitles',
			},
			{
				id: 8,
				label: 'Spanish (Full)',
				file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/media/master/Films/Films/Sintel.(2010)/subtitles/Sintel.(2010).NoMercy.spa.full.vtt',
				language: 'spa',
				kind: 'subtitles',
			},
			{
				id: 9,
				label: 'Polish (Full)',
				file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/media/master/Films/Films/Sintel.(2010)/subtitles/Sintel.(2010).NoMercy.pol.full.vtt',
				language: 'pol',
				kind: 'subtitles',
			},
			{
				id: 10,
				file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/media/master/Films/Films/Sintel.(2010)/thumbs_256x109.vtt',
				kind: 'thumbnails',
			},
			{
				id: 11,
				file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/media/master/Films/Films/Sintel.(2010)/chapters.vtt',
				kind: 'chapters',
			},
			{
				id: 12,
				file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/media/master/Films/Films/Sintel.(2010)/thumbs_256x109.webp',
				kind: 'sprite',
			},
		],
	},
	{
		id: 'cosmos-laundromat',
		title: 'Cosmos Laundromat',
		description: 'On a desolate island, a suicidal sheep named Franck meets his fate…in the form of a quirky salesman named Victor, who offers him the gift of a lifetime. The gift is many lifetimes, actually, in many different worlds – each lasting just a few minutes. In the sequel to the pilot, Franck will find a new reason to live…in the form of a bewitching female adventurer named Tara, who awakens his long-lost lust for life. But can Franck keep up with her?',
		image: 'https://image.tmdb.org/t/p/w780/f2wABsgj2lIR2dkDEfBZX8p4Iyk.jpg',
		logo: 'https://image.tmdb.org/t/p/original/kJL8smUGlQ29mPLcook393vYt4X.png',
		file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/media/master/Films/Films/Cosmos.Laundromat.(2015)/Cosmos.Laundromat.(2015).NoMercy.m3u8',
		duration: '12:04',
		year: 2015,
		rating: {
			rating: 12,
			image: 'NL/NL_12.svg',
		},
		tracks: [
			{
				id: 0,
				label: 'Dutch (Full)',
				file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/media/master/Films/Films/Cosmos.Laundromat.(2015)/subtitles/Cosmos.Laundromat.(2015).NoMercy.dut.full.vtt',
				language: 'dut',
				kind: 'subtitles',
			},
			{
				id: 1,
				label: 'English (Full)',
				type: 'sdh',
				file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/media/master/Films/Films/Cosmos.Laundromat.(2015)/subtitles/Cosmos.Laundromat.(2015).NoMercy.eng.full.vtt',
				language: 'eng',
				kind: 'subtitles',
			},
			{
				id: 2,
				label: 'French (Full)',
				file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/media/master/Films/Films/Cosmos.Laundromat.(2015)/subtitles/Cosmos.Laundromat.(2015).NoMercy.fre.full.vtt',
				language: 'fre',
				kind: 'subtitles',
			},
			{
				id: 3,
				label: 'Italian (Full)',
				file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/media/master/Films/Films/Cosmos.Laundromat.(2015)/subtitles/Cosmos.Laundromat.(2015).NoMercy.ita.full.vtt',
				language: 'ita',
				kind: 'subtitles',
			},
			{
				id: 4,
				label: 'Brazilian Portuguese (Full)',
				file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/media/master/Films/Films/Cosmos.Laundromat.(2015)/subtitles/Cosmos.Laundromat.(2015).NoMercy.pob.full.vtt',
				language: 'pob',
				kind: 'subtitles',
			},
			{
				id: 5,
				label: 'Spanish (Full)',
				file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/media/master/Films/Films/Cosmos.Laundromat.(2015)/subtitles/Cosmos.Laundromat.(2015).NoMercy.spa.full.vtt',
				language: 'spa',
				kind: 'subtitles',
			},
			{
				id: 6,
				file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/media/master/Films/Films/Cosmos.Laundromat.(2015)/thumbs_256x144.vtt',
				kind: 'thumbnails',
			},
			{
				id: 7,
				file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/media/master/Films/Films/Cosmos.Laundromat.(2015)/chapters.vtt',
				kind: 'chapters',
			},
			{
				id: 8,
				file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/media/master/Films/Films/Cosmos.Laundromat.(2015)/thumbs_256x144.webp',
				kind: 'sprite',
			},
		],
	},
	{
		id: 'big-buck-bunny',
		title: 'Big Buck Bunny',
		description: 'Big Buck Bunny tells the story of a giant rabbit with a heart bigger than himself. When one sunny day three rodents rudely harass him, something snaps... and the rabbit ain\'t no bunny anymore! In the typical cartoon tradition he prepares the nasty rodents a comical revenge.',
		image: 'https://image.tmdb.org/t/p/original/xtdybjRRZ15mCrPOvEld305myys.jpg',
		logo: 'https://image.tmdb.org/t/p/original/fW0heBZpksNXSNAeLl0wT2N7cD3.svg',
		file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/media/master/Films/Films/Big.Buck.Bunny.(2008)/Big.Buck.Bunny.(2008).NoMercy.m3u8',
		duration: '9:56',
		year: 2015,
		rating: {
			rating: 12,
			image: 'NL/NL_AL.svg',
		},
		tracks: [
			{
				id: 0,
				file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/media/master/Films/Films/Big.Buck.Bunny.(2008)/thumbs_320x178.vtt',
				kind: 'thumbnails',
			},
			{
				id: 1,
				file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/media/master/Films/Films/Big.Buck.Bunny.(2008)/chapters.vtt',
				kind: 'chapters',
			},
			{
				id: 2,
				file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/media/master/Films/Films/Big.Buck.Bunny.(2008)/thumbs_320x178.webp',
				kind: 'sprite',
			},
		],
	},
	{
		id: 'tears-of-steel',
		title: 'Tears of Steel',
		description: 'Tears of Steel was realized with crowd-funding by users of the open source 3D creation tool Blender. Target was to improve and test a complete open and free pipeline for visual effects in film - and to make a compelling sci-fi film in Amsterdam, the Netherlands.  The film itself, and all raw material used for making it, have been released under the Creatieve Commons 3.0 Attribution license. Visit the tearsofsteel.org website to find out more about this, or to purchase the 4-DVD box with a lot of extras.  (CC) Blender Foundation - https://www.tearsofsteel.org',
		image: 'https://image.tmdb.org/t/p/w780/fOy6SL5Zs2PFcNXwqEPIDPrLB1q.jpg',
		logo: 'https://image.tmdb.org/t/p/original/z189jjuLnQ77QyipJ0i33mGEjiS.png',
		file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/media/master/Films/Films/Tears.of.Steel.(2012)/Tears.of.Steel.(2012).NoMercy.m3u8',
		duration: '12:13',
		year: 2012,
		rating: {
			rating: 6,
			image: 'NL/NL_6.svg',
		},
		tracks: [
			{
				id: 0,
				label: 'Brazilian (Full)',
				type: 'sdh',
				file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/media/master/Films/Films/Tears.of.Steel.(2012)/subtitles/Tears.of.Steel.(2012).NoMercy.bra.full.vtt',
				language: 'bra',
				kind: 'subtitles',
			},
			{
				id: 1,
				label: 'Chinese (Full)',
				type: 'sdh',
				file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/media/master/Films/Films/Tears.of.Steel.(2012)/subtitles/Tears.of.Steel.(2012).NoMercy.chi.full.vtt',
				language: 'chi',
				kind: 'subtitles',
			},
			{
				id: 2,
				label: 'Croatian (Full)',
				type: 'sdh',
				file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/media/master/Films/Films/Tears.of.Steel.(2012)/subtitles/Tears.of.Steel.(2012).NoMercy.cro.full.vtt',
				language: 'cro',
				kind: 'subtitles',
			},
			{
				id: 3,
				label: 'Chech (Full)',
				type: 'sdh',
				file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/media/master/Films/Films/Tears.of.Steel.(2012)/subtitles/Tears.of.Steel.(2012).NoMercy.cze.full.vtt',
				language: 'cze',
				kind: 'subtitles',
			},
			{
				id: 4,
				label: 'Danish (Full)',
				type: 'sdh',
				file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/media/master/Films/Films/Tears.of.Steel.(2012)/subtitles/Tears.of.Steel.(2012).NoMercy.dan.full.vtt',
				language: 'dan',
				kind: 'subtitles',
			},
			{
				id: 5,
				label: 'Dutch (Full)',
				type: 'sdh',
				file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/media/master/Films/Films/Tears.of.Steel.(2012)/subtitles/Tears.of.Steel.(2012).NoMercy.dut.full.vtt',
				language: 'dut',
				kind: 'subtitles',
			},
			{
				id: 6,
				label: 'English (Full)',
				type: 'sdh',
				file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/media/master/Films/Films/Tears.of.Steel.(2012)/subtitles/Tears.of.Steel.(2012).NoMercy.eng.full.vtt',
				language: 'eng',
				kind: 'subtitles',
			},
			{
				id: 7,
				label: 'French (Full)',
				type: 'sdh',
				file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/media/master/Films/Films/Tears.of.Steel.(2012)/subtitles/Tears.of.Steel.(2012).NoMercy.fre.full.vtt',
				language: 'fre',
				kind: 'subtitles',
			},
			{
				id: 8,
				label: 'German (Full)',
				type: 'sdh',
				file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/media/master/Films/Films/Tears.of.Steel.(2012)/subtitles/Tears.of.Steel.(2012).NoMercy.ger.full.vtt',
				language: 'ger',
				kind: 'subtitles',
			},
			{
				id: 9,
				label: 'Greek (Full)',
				type: 'sdh',
				file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/media/master/Films/Films/Tears.of.Steel.(2012)/subtitles/Tears.of.Steel.(2012).NoMercy.gre.full.vtt',
				language: 'gre',
				kind: 'subtitles',
			},
			{
				id: 10,
				label: 'Hebrew (Full)',
				type: 'sdh',
				file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/media/master/Films/Films/Tears.of.Steel.(2012)/subtitles/Tears.of.Steel.(2012).NoMercy.heb.full.vtt',
				language: 'heb',
				kind: 'subtitles',
			},
			{
				id: 11,
				label: 'Hungarian (Full)',
				type: 'sdh',
				file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/media/master/Films/Films/Tears.of.Steel.(2012)/subtitles/Tears.of.Steel.(2012).NoMercy.hun.full.vtt',
				language: 'hun',
				kind: 'subtitles',
			},
			{
				id: 12,
				label: 'Indian (Full)',
				type: 'sdh',
				file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/media/master/Films/Films/Tears.of.Steel.(2012)/subtitles/Tears.of.Steel.(2012).NoMercy.ind.full.vtt',
				language: 'ind',
				kind: 'subtitles',
			},
			{
				id: 13,
				label: 'Italian (Full)',
				type: 'sdh',
				file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/media/master/Films/Films/Tears.of.Steel.(2012)/subtitles/Tears.of.Steel.(2012).NoMercy.ita.full.vtt',
				language: 'ita',
				kind: 'subtitles',
			},
			{
				id: 14,
				label: 'Japanese (Full)',
				type: 'sdh',
				file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/media/master/Films/Films/Tears.of.Steel.(2012)/subtitles/Tears.of.Steel.(2012).NoMercy.jpn.full.vtt',
				language: 'jpn',
				kind: 'subtitles',
			},
			{
				id: 15,
				label: 'Norwegian (Full)',
				type: 'sdh',
				file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/media/master/Films/Films/Tears.of.Steel.(2012)/subtitles/Tears.of.Steel.(2012).NoMercy.nor.full.vtt',
				language: 'nor',
				kind: 'subtitles',
			},
			{
				id: 16,
				label: 'Persian (Full)',
				type: 'sdh',
				file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/media/master/Films/Films/Tears.of.Steel.(2012)/subtitles/Tears.of.Steel.(2012).NoMercy.per.full.vtt',
				language: 'per',
				kind: 'subtitles',
			},
			{
				id: 17,
				label: 'Portugese (Full)',
				type: 'sdh',
				file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/media/master/Films/Films/Tears.of.Steel.(2012)/subtitles/Tears.of.Steel.(2012).NoMercy.por.full.vtt',
				language: 'por',
				kind: 'subtitles',
			},
			{
				id: 18,
				label: 'Russian (Full)',
				type: 'sdh',
				file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/media/master/Films/Films/Tears.of.Steel.(2012)/subtitles/Tears.of.Steel.(2012).NoMercy.rus.full.vtt',
				language: 'rus',
				kind: 'subtitles',
			},
			{
				id: 19,
				label: 'Spanish (Full)',
				type: 'sdh',
				file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/media/master/Films/Films/Tears.of.Steel.(2012)/subtitles/Tears.of.Steel.(2012).NoMercy.spa.full.vtt',
				language: 'spa',
				kind: 'subtitles',
			},
			{
				id: 20,
				file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/media/master/Films/Films/Tears.of.Steel.(2012)/previews.vtt',
				kind: 'thumbnails',
			},
			{
				id: 21,
				file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/media/master/Films/Films/Tears.of.Steel.(2012)/chapters.vtt',
				kind: 'chapters',
			},
			{
				id: 22,
				file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/media/master/Films/Films/Tears.of.Steel.(2012)/sprite.webp',
				kind: 'sprite',
			},
		],
	},
	{
		id: 'bipbop',
		title: 'BipBop',
		description: 'BipBop is a video test media file from Apple. It is used to test HLS streaming and player functionality. The media file is a 30-minute video of a person talking and includes a subtitle track in English. The video is encoded in H.264 and the audio is encoded in AAC. The subtitle track is encoded in WebVTT format',
		image: 'https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/poster.png',
		file: 'https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8',
		duration: '30:00',
		rating: {
			rating: 0,
			image: 'NL/NL_ALL.svg',
		},
		tracks: [
			{
				id: 0,
				label: 'English (Full)',
				file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/Examples/refs/heads/master/public/example_subtitle.vtt',
				language: 'eng',
				kind: 'subtitles',
			},
		],
	},
	{
		id: 'rail-wars',
		title: 'Rail Wars',
		description: 'Takayama enters the training program of JNR with the ambition of becoming one of the venerable train company\'s engineers. As a trainee he is teamed up with fight-ready Sakurai and stolid Iwaizumi and fellow Haruka Kōmi who has encyclopedic knowledge of trains. Together they learn how security officers for the train line work and get involved in more than one tricky situation.',
		image: 'https://image.tmdb.org/t/p/original/vH8NqN2LMcmtBv037iHGwcPOgCZ.jpg',
		file: 'https://backstore.fra1.digitaloceanspaces.com/demo/railwars/railwars.mp4',
		duration: '1:30',
		rating: {
			rating: 6,
			image: 'NL/NL_6.svg',
		},
		tracks: [
			{
				id: 0,
				label: 'English (Full)',
				file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/media/refs/heads/master/Anime/Anime/Rail.Wars!.(2014)/Rail.Wars!.S00E00/subtitles/Rail.Wars!.(2014).S00E00.NoMercy.eng.full.ass',
				language: 'eng',
				kind: 'subtitles',
			},
			{
				id: 1,
				file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/media/refs/heads/master/Anime/Anime/Rail.Wars!.(2014)/Rail.Wars!.S00E00/fonts.json',
				kind: 'fonts',
			},
		],
	},
	{
		id: 'no-rin',
		title: 'No-Rin',
		description: 'The sudden retirement of the famous idol Yuka Kusakabe from the entertainment business shocks the world and devastates her biggest fan, teenager Kosaku Hata. His classmates at the Tamo Agriculture School manages to get him out of his depression and bring him out of his room to attend his classes. But to everyone\'s surprise, Yuka Kusakabe - her stage name - comes into their class under the name Ringo Kinoshita as a transfer student. Kosaku realizes he has a once-in-a-lifetime opportunity to get to personally know his dream girl and, together with his group of friends, try to find out why she came to the agricultural school and become more than just classmates.',
		rating: {
			rating: 9,
			image: 'NL/NL_9.svg',
		},
		image: 'https://image.tmdb.org/t/p/original/myHS6X2yonpoBQOptVuQ85PudtC.jpg',
		file: 'https://backstore.fra1.digitaloceanspaces.com/demo/nourin/nourin.mp4',
		duration: '23:39',
		tracks: [
			{
				id: 0,
				label: 'English (Full)',
				file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/media/refs/heads/master/Anime/Anime/No-Rin.(2014)/No-Rin.S00E00/subtitles/No-Rin.(2014).S00E00.NoMercy.eng.full.ass',
				language: 'eng',
				kind: 'subtitles',
			},
			{
				id: 1,
				file: 'https://raw.githubusercontent.com/NoMercy-Entertainment/media/refs/heads/master/Anime/Anime/No-Rin.(2014)/No-Rin.S00E00/fonts.json',
				kind: 'fonts',
			},
		],
	},
].map((e, i) => ({...e, episode: i + 1}));

export default playlist;